apiVersion: v1
kind: Service
metadata:
    name: jogador
    labels:
        name: jogador
spec:
    type: NodePort
    ports:
        - port: 8080
          targetPort: 8080
          protocol: TCP
    selector:
        app: jogador